### ISSUE TITLE
Error (Linux)

### ISSUE THREAD

**Issue by rafaelsupport** [truedread/pymp4decrypt#6]
suporte@SUP-13:~/pymp4decrypt/src$ python decrypt.py -k 4ce68c303ae037a59888d4866de39ffb -i ~/Blank\ -\ A\ Vinylmation\ Love\ Story-FitJ3hgxiAg.mp4 -o ~/Blank.mp4
Traceback (most recent call last):
  File "decrypt.py", line 131, in <module>
    main()
  File "decrypt.py", line 50, in main
    decrypt(args.key, args.input, args.output)
  File "decrypt.py", line 78, in decrypt
    with BufferedReader(inp) as reader:
AttributeError: 'file' object has no attribute 'readable'

**Comment by Puyodead1** [comment]
Same problem on Ubuntu 18.04

**Comment by tungtrandt13** [comment]
Same problem on Ubuntu 16.04 python version 2.7.12

**Comment by fastfading** [comment]
same on mac
